version: '3.8'

services:
  db:
    image: postgres:14.1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: upskills
  adminer:
    image: adminer
    ports:
      - 8090:8080
  app:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: upskills
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_QUEUE_URL: ${AWS_URL:-url}
    ports:
      - 8000:8080