version: '3.8'

services:
  db:
    image: postgres:14.1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: upskills
  adminer:
    image: adminer
    ports:
      - 8090:8080

