CREATE TABLE speaker (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   phone_number VARCHAR(255),
   email VARCHAR(255),
   bio TEXT,
   status VARCHAR(255),
   CONSTRAINT pk_speaker PRIMARY KEY (id)
);

CREATE TABLE conference (
  id UUID NOT NULL,
   name VARCHAR(255) NOT NULL,
   title VARCHAR(255) NOT NULL,
   number_of_places INTEGER NOT NULL,
   status INTEGER,
   amount DECIMAL,
   currency VARCHAR(255),
   start_date TIMESTAMP WITHOUT TIME ZONE,
   end_date TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_conference PRIMARY KEY (id)
);