CREATE TABLE speech(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
conference_id UUID,
start_date TIMESTAMP WITHOUT TIME ZONE,
end_date TIMESTAMP WITHOUT TIME ZONE,
title VARCHAR(250) NOT NULL,
CONSTRAINT pk_speech PRIMARY KEY (id),
CONSTRAINT fk_conference FOREIGN KEY(conference_id) REFERENCES conference(id)
     );

CREATE TABLE speech_speaker_set(
speech_id BIGINT,
speaker_set_id BIGINT,
PRIMARY KEY (speech_id, speaker_set_id),
  CONSTRAINT fk_speech FOREIGN KEY(speech_id) REFERENCES speech(id),
  CONSTRAINT fk_speaker FOREIGN KEY(speaker_set_id) REFERENCES speaker(id)
);